# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bEaCLbr6sFoQLMnI5oj8kxaSs2RH13On
"""

!pip install -q -U google-genai

class Interaction():
    def __init__(self, q, empathy, q_type, ans, ):
        self.q = q
        self.empathy = empathy #bool, true - empathetic mode
        self.q_type = q_type
        self.ans = ans
        self.assessment = None

    def get_asessment(self):
        # code to get llm to assess person on a scale of the test based on their answer
        self.ass = 666
        return self.ass

import pandas as pd

def get_csv(path):
    df = pd.read_csv(path)


    return df[["questionnaire", "question_neutral", "question_empathy"]]

df = get_csv("/content/question_tree.csv")
df.head(10)

from google import genai

client = genai.Client(api_key="AIzaSyB1lOGJjWwtpPDacN4QPlJgr2QzdcJFUyE")


def get_prompt(q,a,next_q ,preprompt=""):
    prepromt = "Over the last 2 weeks, how often have you been bothered by the following problems?"
    categories = '["Not at all (0)", "Several days (+1)", "More than half the days (+2)", "Nearly every day (+3)"]'


    return f"You are an empathic robot that does weekly mental health checkins with university students. \
            The check-ins are really time constraint so it is important to keep the talk concise (your answer should be max 2 sentences). \
            Answer in a friendly, empathic way, humor and adding emotions is okay. The student is supposed to gain trust in you. \
            You are keeping the conversation going, the test subject just answered the question: \
            <({preprompt}) {q}> with <{a}> \
            First, map this answer to one of the categories: {categories}\
            Then give a short empathic appropriate response or other fitting emotional expression and connect it with the next question \
            <({preprompt}) {next_q}> that you are asking. You can do only minor changes to the next question text.\
            Besides that provide an emotion for robot's reaction as an integer on a scale from 1 to 10 (1 being sad, 10 being happy).\
            Provide your response in JSON format with the following structure: (user_answer_category: integer, next_communication: string, robot_emotion: integer)"

q = "How often did you feel nervous or anxious and had trouble relaxing"
a = "I am not nervous at all, its going pretty well"
next_q = "Did you worry about different things too much, or it was difficult to control it?"
prompt = get_prompt(q,a,next_q)



response = client.models.generate_content(
    model="gemini-3-flash-preview", contents=prompt
)

print(response.text)

for index, row in df.iterrows():
    row["qestion"]

